### ISSUE TITLE
migration: Circulation data migration from invenio v1

### ISSUE THREAD

**Issue by david-caro** [inveniosoftware-attic/invenio-circulation-legacy#54]
Scripts to migrate existing circulation data on an invenio 1 system to the new format.

**Comment by egabancho** [comment]
Should we move this issue to [invenio-migrator](https://github.com/inveniosoftware/invenio-migrator)?

**Comment by egabancho** [comment]
continues in https://github.com/inveniosoftware/invenio-migrator/issues/62
